# Generated by Django 4.2 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finding_china", "0004_question_customuser_progreso_contribuciones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="opcion1",
            field=models.JSONField(
                default={"es_respuesta_correcta": "", "texto_opcion": ""}
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="opcion2",
            field=models.JSONField(
                default={"es_respuesta_correcta": "", "texto_opcion": ""}
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="opcion3",
            field=models.JSONField(
                default={"es_respuesta_correcta": "", "texto_opcion": ""}
            ),
        ),
    ]
