# Generated by Django 4.2 on 2023-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finding_china", "0005_question_opcion1_question_opcion2_question_opcion3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="opcion1",
            field=models.JSONField(
                default={"es_respuesta_correcta": False, "texto_opcion": ""}
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="opcion2",
            field=models.JSONField(
                default={"es_respuesta_correcta": False, "texto_opcion": ""}
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="opcion3",
            field=models.JSONField(
                default={"es_respuesta_correcta": False, "texto_opcion": ""}
            ),
        ),
    ]
