# Generated by Django 4.2 on 2023-06-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finding_china",
            "0006_alter_question_opcion1_alter_question_opcion2_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Option",
        ),
    ]
