# Generated by Django 4.2 on 2023-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finding_china", "0007_delete_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="aciertos_contribuciones",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="aciertos_cultura",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="aciertos_historia",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="fallos_contribuciones",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="fallos_cultura",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="fallos_historia",
            field=models.IntegerField(default=0),
        ),
    ]
